name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**'
      - 'README.md'

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
          svg_path: assets/github-contribution-grid-snake.svg

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'assets/*.svg'
          message: 'Update snake animation [skip ci]'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          tag: 'snake-update'
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}